### ISSUE TITLE
Support for more advanced glm.array typing.

### ISSUE THREAD

**Issue by williamhCode** [esoma/pyglm-typing#4]
In python, you can type lists and specify its data type, such as `a_list: list[int]`. However, doing this with glm.array doesn't work when I did `vertices: glm.array[glm.float32]`, and it shows `TypeError: 'type' object is not subscriptable`. Is it possible to add this way of typing with glm arrays? 

Surprisingly, even with the runtime error, Vscode displays everything nicely, and even shows the type information as `(variable) vertices: array[c_float]`.

**Comment by esoma** [comment]
Hi, this is a limitation of PyGLM itself, see this issue: https://github.com/Zuzu-Typ/PyGLM/pull/172

For the particular case you're encountering, you may use `from __future__ import annotations` so that python does not evaluate annotations at runtime as objects, but strings instead. Alternatively you can make your annotation a string:
```python
a_list: "list[int]"
```

**Comment by williamhCode** [comment]
Thanks for the reply, adding quotes work finely.
